USE GESTAO_HOTEL
GO

/*USE [master]
GO
ALTER DATABASE [GESTAO_HOTEL] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE [master]
GO
DROP DATABASE [GESTAO_HOTEL]
GO*/

--COMANDOS PARA INSERÇÃO

--SEXO
INSERT INTO SEXO VALUES(1,'Feminino')
INSERT INTO SEXO VALUES(2,'Masculino')

--FUNCIONARIO
INSERT INTO FUNCIONARIO VALUES('000000000','Administrador','admin@gmail.com','0000000-0000','Rua A1, 010','admin','admin',1,1,GETDATE())

--GRUPO_FUNCIONARIO
INSERT INTO GRUPO_FUNCIONARIO(NOME_GRUPO)VALUES('Administrador')
INSERT INTO GRUPO_FUNCIONARIO(NOME_GRUPO)VALUES('Gerente')
INSERT INTO GRUPO_FUNCIONARIO(NOME_GRUPO)VALUES('Recepsionista')
INSERT INTO GRUPO_FUNCIONARIO(NOME_GRUPO)VALUES('Gorvenanta')

--PERMISSAO
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Visualizar funcionário') --1
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Cadastrar funcionário') --2
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Alterar funcionário') --3
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Excluir funcionário') --4
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Visualizar grupo de funcionário') --5
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Cadastrar grupo de funcionário') --6
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Alterar grupo de funcionário') --7
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Excluir grupo de funcionário') --8
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Visualizar cliente') --9
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Cadastrar cliente') --10
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Alterar cliente') --11
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Excluir cliente') --12
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Visualizar diária') --13
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Cadastrar diária') --14
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Alterar diária') --15
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Excluir diária') --16
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Visualizar quarto') --17
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Cadastrar quarto') --18
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Alterar quarto') --19
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Excluir quarto') --20
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Adicionar permissão a um grupo de funcionário') --21
INSERT INTO PERMISSAO(DESCRICAO)VALUES('Adicionar grupo de funcionário a um funcionário') --22

--PERMISSAO_GRUPO_FUNCIONARIO
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,1)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,2)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,3)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,4)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,5)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,6)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,7)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,8)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,9)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,10)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,11)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,12)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,13)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,14)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,15)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,16)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,17)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,18)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,19)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,20)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,21)
INSERT INTO PERMISSAO_GRUPO_FUNCIONARIO(ID_GRUPO_FUNCIONARIO,ID_PERMISSAO)VALUES(1,22)

--FUNCIONARIO_GRUPO_FUNCIONARIO
INSERT INTO FUNCIONARIO_GRUPO_FUNCIONARIO(ID_FUNCIONARIO,ID_GRUPO_FUNCIONARIO)VALUES(1,1)


--COMANDOS PARA SELECT

SELECT * FROM FUNCIONARIO
SELECT * FROM SEXO
SELECT * FROM GRUPO_FUNCIONARIO
SELECT * FROM FUNCIONARIO_GRUPO_FUNCIONARIO
SELECT * FROM PERMISSAO
SELECT * FROM PERMISSAO_GRUPO_FUNCIONARIO